POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test01@gmail.com",
    "password": "123"
    
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test01@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MDFAZ21haWwuY29tIiwiaWF0IjoxNjY4ODc0NzMzLCJleHAiOjE2Njg4NzQ3NjN9.hAYKHaxQE1VTVwAqNObS1LJZvNsleLciBL4G4Q4-zwo
