POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "test01@gmail.com",
    "password": "123"
    
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test01@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MDFAZ21haWwuY29tIiwiaWF0IjoxNjY4OTUxNjM1LCJleHAiOjE2Njg5NTE2NjV9.a51SL0XFXmWT6neQM_MyGEqZjU9iCya2ijElaCl_Sn0
